server:
 port: 8082

spring:
 application:
  name: HotelService
 datasource:
  url: jdbc:postgresql://localhost:5432/microservice
  username: postgres
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 config:
  import: optional:configserver:http://localhost:6666   
  
okta:
 oauth2:
  issuer: https://dev-24066838.okta.com/oauth2/default 
  audience: api://default  